### ISSUE TITLE
Some message files are missing

### ISSUE THREAD

**Issue by ghost** [lijx10/uwb-localization#1]
Hi Li Jiaxin,

Thank you for publishing this interesting piece of code.
It looks like the common_msgs package is missing some of the custom messages namely:
 NavigationState.msg
  GPSVelocity.msg
  MeasurementPosition.msg
  MeasurementVelocity.msg
  PixhawkCMD.msg
  PixhawkServo.msg
  MeasurementPosVel.msg
  MaxDynamics.msg
  Reference.msg
  Mission.msg
  MissionStatus.msg
  PathPlanningStatus.msg
  Waypoint.msg

and this stops me from building the code.

Would you please add them to the repo or give me directions if they are available somewhere?
thanks

**Comment by lijx10** [comment]
I have uploaded them to the repository. However, this repository is actually part of a general library for UAVs, and it is not supposed to be compiled and run without other components of that library. Unfortunately, I can't release that library because of Intellectual Property issues. 

The localization algorithm is in `uwb-localization/slam_pp/src/slam/`, and the entry is `thread_slam.cpp`
The calibration algorithm is in `uwb-localization/uwb_calibration/src/`, and the entry is `uwb_calibration_node.cpp`
